# Generated by Django 3.1.5 on 2021-01-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='age',
            field=models.IntegerField(),
        ),
    ]
